// This file is generated by Gemini.
'use server';
/**
 * @fileOverview An AI-powered tool that rewrites and optimizes the text content on a portfolio page.
 *
 * - optimizeContent - A function that handles the content optimization process.
 * - OptimizeContentInput - The input type for the optimizeContent function.
 * - OptimizeContentOutput - The return type for the optimizeContent function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const OptimizeContentInputSchema = z.object({
  content: z.string().describe('The text content to be optimized.'),
  targetAudience: z.string().describe('The target audience for the content (e.g., potential employer, specific industry).'),
});
export type OptimizeContentInput = z.infer<typeof OptimizeContentInputSchema>;

const OptimizeContentOutputSchema = z.object({
  optimizedContent: z.string().describe('The optimized text content tailored for the target audience.'),
});
export type OptimizeContentOutput = z.infer<typeof OptimizeContentOutputSchema>;

export async function optimizeContent(input: OptimizeContentInput): Promise<OptimizeContentOutput> {
  return optimizeContentFlow(input);
}

const prompt = ai.definePrompt({
  name: 'optimizeContentPrompt',
  input: {schema: OptimizeContentInputSchema},
  output: {schema: OptimizeContentOutputSchema},
  prompt: `You are an AI-powered tool that rewrites and optimizes text content for a portfolio page.

  Your goal is to tailor the content to match the target audience, highlighting the most relevant skills and experience.

  Original Content: {{{content}}}
  Target Audience: {{{targetAudience}}}

  Please provide an optimized version of the content that is more appealing and relevant to the specified target audience.`,
});

const optimizeContentFlow = ai.defineFlow(
  {
    name: 'optimizeContentFlow',
    inputSchema: OptimizeContentInputSchema,
    outputSchema: OptimizeContentOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
